### ISSUE TITLE
Plock now breaks due to changes in setuptools

### ISSUE THREAD

**Issue by pigeonflight** [plock/plock#24]
running the command:

    plock helloplone

Results in the following output

    Traceback (most recent call last):
      File "/home/action/pndk/bin/plock", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/home/action/pndk/local/lib/python2.7/site-packages/pkg_resources.py", line 2829, in <module>
        working_set = WorkingSet._build_master()
      File "/home/action/pndk/local/lib/python2.7/site-packages/pkg_resources.py", line 451, in _build_master
        return cls._build_from_requirements(__requires__)
      File "/home/action/pndk/local/lib/python2.7/site-packages/pkg_resources.py", line 464, in _build_from_requirements
        dists = ws.resolve(reqs, Environment())
      File "/home/action/pndk/local/lib/python2.7/site-packages/pkg_resources.py", line 639, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: setuptools>=8.0

**Comment by pigeonflight** [comment]
It looks like we'll need to "pin" the version of setuptools somewhere, to ensure that plock is using a compatible version of setuptools.

**Comment by aclark4life** [comment]
It's already pinned: https://github.com/plock/pins/commit/f63f52b544a44794c515af6f1b8085a489dc054f

**Comment by fulv** [comment]
I just tried a brand-new install, and got the same error.

**Comment by aclark4life** [comment]
@fulv You probably need to upgrade your setuptools

**Comment by fulv** [comment]
I know, I just thought I'd mention it.  Wouldn't want roadblocks like this
to making Plock live up to the expectations you set.

**Comment by aclark4life** [comment]
@fulv Sure, thanks. Plock should probably catch that error and provide helpful instruction.

**Comment by dgroos** [comment]
The new plock as per: http://blog.aclark.net/2015/10/10/plock-0-5-0-is-out/ sounded alluring! I tried it in a Virtualbox instance running Ubuntu server 14.04.3. Had already installed different Plone 4.x in this vbox instance. I also ran into: 
"pkg_resources.DistributionNotFound: setuptools>=8.0"
Upon trying to update my setuptools with "sudo apt-get install python-setuptools" I got: 
"python-setuptools is already the newest version"
Would someone let me know how to proceed? Thanks.

**Comment by aclark4life** [comment]
@dgroos Can you try outside of an existing virtualenv?

**Comment by dgroos** [comment]
Sure. For example create a new virtualbox instance and install fresh ubuntu server 14.04? or install 15.04?

**Comment by aclark4life** [comment]
@dgroos Oh sorry, I misread. Try upgrading setuptools with something like:

```
wget https://bootstrap.pypa.io/ez_setup.py -O - | python
```

(from https://pypi.python.org/pypi/setuptools#unix-wget)

**Comment by dgroos** [comment]
Thanks, the install proceeded successfully (I did as root user)!
When it tried to launch in fg as per your instructions I got this:
INFO ZServer HTTP server started at Sat Oct 10 14:02:20 2015
	Hostname: 0.0.0.0
	Port: 8080
2015-10-10 14:02:20 CRITICAL Zope A user was not specified to setuid to; fix this to start as root (change the effective-user directive in zope.conf)

**Comment by aclark4life** [comment]
You probably don't want to be using root to install Plone, can you try another user e.g. ``www-data`` on Ubuntu, maybe. As root, you can ``sudo su - www-data`` then run the install and start Plone.

**Comment by dgroos** [comment]
Tried to install with www-data user and couldn't overcome issues (though only spent 15 min trying).

OK! Looks like I needed root user for first command (pip install plock) only. All the rest of the commands worked as my own user when running them in my home directory, including successfully started site in fg.

Then, when going to instance in a browser, tried to create a new site and it requested the zope user authentication info (user/pass) which I didn't have. Should it have printed this out in terminal?
(sorry to have this dialog here, should I move to another page?)

**Comment by aclark4life** [comment]
No this is fine, try admin:admin

**Comment by dgroos** [comment]
Got me in! 

I found that when I tried then to make the site, I got the error that:
ImportError: No module named _tkinter, please install the python-tk package"
After sudo apt-get install python-tk", install of a plone site worked and I've got a working plone site. Never seen anything this simple for installing Plone (once I had setuptools updated etc). I recommend you add the admin:admin user/pass info on the web page for people such as myself who aren't in-the-know. This is awesome @aclark4life -- thanks for your cool work. Looking forward to playing with the official release of Plone5.
David G

**Comment by aclark4life** [comment]
@dgroos Great! Glad to hear. Added login info to the README

**Comment by dgroos** [comment]
Nice. Not sure if there is an appropriate place, maybe an install.txt file
for neophytes such as myself, with tips such as the command you gave me to
update setuptools and also of the need to install python-tk. There may be
other files required in Ubuntu server 14.3, but I already had them taken
care of since I had previously install Plone 4 in that VM. Probably there's
already a page out there on plone.org or elsewhere that tells of this so
maybe a link to that page would be best. Best of luck.

**Comment by aclark4life** [comment]
@dgroos All good suggestions, thanks! I've added instructions for setuptools & OS requirements here:
- https://github.com/plock/plock#setuptools-errors
- https://github.com/plock/plock#missing-requirements

**Comment by dgroos** [comment]
Cool :-) 
When I checked the plone page about "system software and libraries to run plone" I didn't see mentioned installing the module _tkinter with python-tk, or perhaps it is a sub-set of one of the other libraries/packages mentioned in the list?

**Comment by aclark4life** [comment]
@dgroos Not sure, could be Pillow I guess: http://pillow.readthedocs.org/en/3.0.x/installation.html#external-libraries
